# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  cm.invoice.twig_extension:
    class: AppBundle\Twig\InvoiceExtension
    public: false
    tags:
      - { name: twig.extension }